Schema.voices.Add("Redshirt", "all day long", "All day long.", "vo/player/redshirt/coggearchatter_alldaylong_loud01.ogg")
Schema.voices.Add("Redshirt", "are you kidding", "A-Are you kidding me!?", "vo/player/redshirt/coggearchatter_areyoukiddingme_med01.ogg")
Schema.voices.Add("Redshirt", "aw yeah", "Aw, yeah!", "vo/player/redshirt/coggearchatter_awyeah_loud02.ogg")
Schema.voices.Add("Redshirt", "bring it", "Bring it!", "vo/player/redshirt/coggearchatter_bringit_loud02.ogg")
Schema.voices.Add("Redshirt", "can always use more", "Can always use more!", "vo/player/redshirt/coggearchatter_canalwaysusemore_med01.ogg")
Schema.voices.Add("Redshirt", "come get me", "Come get me!", "vo/player/redshirt/coggearchatter_comegetme_loud01.ogg")
Schema.voices.Add("Redshirt", "crawl your ass", "Crawl your ass back here!", "vo/player/redshirt/coggearchatter_crawlyourassbackhere_loud02.ogg")
Schema.voices.Add("Redshirt", "damnit", "Damnit!", "vo/player/redshirt/coggearchatter_dammit_loud01.ogg")
Schema.voices.Add("Redshirt", "dont mind if I", "Don't mind if I do.", "vo/player/redshirt/coggearchatter_dontmindifido_med02.ogg")
Schema.voices.Add("Redshirt", "get some of this", "Get some of this!", "vo/player/redshirt/coggearchatter_getsomeofthis_loud01.ogg")
Schema.voices.Add("Redshirt", "goodnight", "Goodnight!", "vo/player/redshirt/coggearchatter_goodnight_med02.ogg")
Schema.voices.Add("Redshirt", "good to go", "Good to go.", "vo/player/redshirt/coggearchatter_goodtogo_loud04.ogg")
Schema.voices.Add("Redshirt", "good to go!", "Good to go.", "vo/player/redshirt/coggearchatter_goodtogo_loud07.ogg")
Schema.voices.Add("Redshirt", "gotcha", "Gotcha.", "vo/player/redshirt/coggearchatter_gotcha_loud04.ogg")
-- Schema.voices.Add("Redshirt", "gottem", "Got 'em.", "vo/player/redshirt/coggearchatter_gotem_med02.ogg")
-- Schema.voices.Add("Redshirt", "got it", "Got it.", "vo/player/redshirt/coggearchatter_gotit_med02.ogg")
Schema.voices.Add("Redshirt", "great thats just great", "Great! Thats just.. Great!", "vo/player/redshirt/coggearchatter_greatthatsjustgreat_med01.ogg")
Schema.voices.Add("Redshirt", "heelloo", "*Heeeelloooo!*", "vo/player/redshirt/coggearchatter_hello_loud02.ogg")
Schema.voices.Add("Redshirt", "hold up Im not done", "Hoold up, I'm not done with you!", "vo/player/redshirt/coggearchatter_holdupimnotdonewithyou_loud01.ogg")
Schema.voices.Add("Redshirt", "hostile", "Hostiles.", "vo/player/redshirt/coggearchatter_hostiles_loud01.ogg")
Schema.voices.Add("Redshirt", "hostile!", "Hostiles!", "vo/player/redshirt/coggearchatter_hostiles_loud02.ogg")
Schema.voices.Add("Redshirt", "hot gun", "Hot gun! Hot-hot gun!", "vo/player/redshirt/coggearchatter_hotgun_loud01.ogg")
Schema.voices.Add("Redshirt", "hey how about you take point", "Hey, how about *you* take point.", "vo/player/redshirt/coggearchatter_howaboutyoutakepoint_loud01.ogg")
Schema.voices.Add("Redshirt", "if you help this goes faster", "You know, if you *help*. This goes faster.", "vo/player/redshirt/coggearchatter_ifyouhelpthisgoesfaster_loud02.ogg")
Schema.voices.Add("Redshirt", "ill take that", "I'll take that.", "vo/player/redshirt/coggearchatter_illtakethat_med01.ogg")
Schema.voices.Add("Redshirt", "im out", "I'm out!", "vo/player/redshirt/coggearchatter_imout_loud01.ogg")
Schema.voices.Add("Redshirt", "i need a hand", "I need a hand!", "vo/player/redshirt/coggearchatter_ineedahand_loud01.ogg")
Schema.voices.Add("Redshirt", "its empty", "It's empty!", "vo/player/redshirt/coggearchatter_itsempty_loud01.ogg")
Schema.voices.Add("Redshirt", "just hold still", "Just hold still.", "vo/player/redshirt/coggearchatter_justholdstill_med01.ogg")
Schema.voices.Add("Redshirt", "lets dance", "Let's dance!", "vo/player/redshirt/coggearchatter_letsdance_loud01.ogg")
Schema.voices.Add("Redshirt", "lets dance!", "Let's dance!", "vo/player/redshirt/coggearchatter_letsdance_loud02.ogg")
Schema.voices.Add("Redshirt", "lets do this", "Let's do this.", "vo/player/redshirt/coggearchatter_letsdothis_med02.ogg")
Schema.voices.Add("Redshirt", "mine now", "Mine now.", "vo/player/redshirt/coggearchatter_minenow_med02.ogg")
Schema.voices.Add("Redshirt", "my fault", "My fault!", "vo/player/redshirt/coggearchatter_myfault_loud01.ogg")
Schema.voices.Add("Redshirt", "nailed it", "Nailed it!", "vo/player/redshirt/coggearchatter_nailedit_loud02.ogg")
Schema.voices.Add("Redshirt", "need ammo", "Need ammo!", "vo/player/redshirt/coggearchatter_needammo_loud01.ogg")
Schema.voices.Add("Redshirt", "nice!", "Niice!", "vo/player/redshirt/coggearchatter_nice_loud03.ogg")
Schema.voices.Add("Redshirt", "nice", "Nice!", "vo/player/redshirt/coggearchatter_nice_med03.ogg")
Schema.voices.Add("Redshirt", "nighty", "Nighty night!", "vo/player/redshirt/coggearchatter_nightynight_med01.ogg")
Schema.voices.Add("Redshirt", "not again", "Not again..", "vo/player/redshirt/coggearchatter_notagain_med01.ogg")
Schema.voices.Add("Redshirt", "no no take your time", "*No!* No.. Thats *fine*. Take your time.", "vo/player/redshirt/coggearchatter_nothatsfinetakeyourtime_loud02.ogg")
Schema.voices.Add("Redshirt", "oh yeah", "Oh yeah!", "vo/player/redshirt/coggearchatter_ohyeah_loud03.ogg")
Schema.voices.Add("Redshirt", "dead grub", "One dead grub!", "vo/player/redshirt/coggearchatter_onedeadgrub_loud02.ogg")
Schema.voices.Add("Redshirt", "feels good", "*Ooh*, that feels good!", "vo/player/redshirt/coggearchatter_oohthatfeelsgood_loud01.ogg")
Schema.voices.Add("Redshirt", "pop show", "Pop goes the freak show!", "vo/player/redshirt/coggearchatter_popgoesthefreakshow_loud01.ogg")
Schema.voices.Add("Redshirt", "safetys off", "Safetys off.", "vo/player/redshirt/coggearchatter_safetysoff_med02.ogg")
Schema.voices.Add("Redshirt", "see ya", "See ya!", "vo/player/redshirt/coggearchatter_seeya_med02.ogg")
Schema.voices.Add("Redshirt", "shes empty", "She's empty.", "vo/player/redshirt/coggearchatter_shesempty_med01.ogg")
Schema.voices.Add("Redshirt", "shit", "Shhit!", "vo/player/redshirt/coggearchatter_shit_loud01.ogg")
Schema.voices.Add("Redshirt", "shit tough", "Shit they're tough!", "vo/player/redshirt/coggearchatter_shittheyretough_loud02.ogg")
Schema.voices.Add("Redshirt", "shit yeah", "Shit yeah!", "vo/player/redshirt/coggearchatter_shityeah_loud02.ogg")
Schema.voices.Add("Redshirt", "sweet", "Swweeet!", "vo/player/redshirt/coggearchatter_sweet_med01.ogg")
Schema.voices.Add("Redshirt", "take that", "Take that!", "vo/player/redshirt/coggearchatter_takethat_loud01.ogg")
Schema.voices.Add("Redshirt", "take that!", "Take! That!", "vo/player/redshirt/coggearchatter_takethat_loud02.ogg")
Schema.voices.Add("Redshirt", "thatll work", "That'll work.", "vo/player/redshirt/coggearchatter_thatllwork_med01.ogg")
Schema.voices.Add("Redshirt", "all over", "They're all over me!", "vo/player/redshirt/coggearchatter_theyrealloverme_loud01.ogg")
Schema.voices.Add("Redshirt", "uhg perfect", "Ahg-- perfect!", "vo/player/redshirt/coggearchatter_uhgperfect_med01.ogg")
Schema.voices.Add("Redshirt", "watch it", "Watch it!", "vo/player/redshirt/coggearchatter_watchit_loud02.ogg")
Schema.voices.Add("Redshirt", "what you hurt", "Whats the matter, you hurt?!", "vo/player/redshirt/coggearchatter_whatsthematteryouhurt_loud01.ogg")
Schema.voices.Add("Redshirt", "whoops", "Whoops!", "vo/player/redshirt/coggearchatter_whoops_loud01.ogg")
Schema.voices.Add("Redshirt", "whos next", "Who's next!", "vo/player/redshirt/coggearchatter_whosnext_loud02.ogg")
Schema.voices.Add("Redshirt", "youre fired", "You're fired!", "vo/player/redshirt/coggearchatter_yourefired_med01.ogg")
Schema.voices.Add("Redshirt", "youre with me", "You're with me.", "vo/player/redshirt/coggearchatter_yourewithme_med01.ogg")
Schema.voices.Add("Redshirt", "youre with me", "You're with me.", "vo/player/redshirt/coggearchatter_yourewithme_med01.ogg")

Schema.voices.Add("Carmine", "aint so tough", "Ain't so tough!", "vo/player/carmine/carminechatter_aintsotough_loud01.ogg")
Schema.voices.Add("Carmine", "aint so tough are ya", "Haha!-Ain't so tough now, are ya!", "vo/player/carmine/carminechatter_aintsotoughnow_loud01.ogg")
Schema.voices.Add("Carmine", "and dead", "Aand DEAD!", "vo/player/carmine/carminechatter_anddead_loud02.ogg")
Schema.voices.Add("Carmine", "and then there were none", "And then there were none.", "vo/player/carmine/carminechatter_andthentherewerenone_medium01.ogg")
Schema.voices.Add("Carmine", "another dead grub", "Another dead grub!", "vo/player/carmine/carminechatter_anotherdeadgrub_loud02.ogg")
Schema.voices.Add("Carmine", "are you kidding me", "Are you kidding me?!", "vo/player/carmine/carminechatter_areyoukiddingme_loud01.ogg")
Schema.voices.Add("Carmine", "attack", "Attack!", "vo/player/carmine/carminechatter_attack_loud01.ogg")
Schema.voices.Add("Carmine", "beat down", "Beat down!", "vo/player/carmine/carminechatter_beatdown_loud01.ogg")
Schema.voices.Add("Carmine", "burn bitch", "Haha! Burn bitch!", "vo/player/carmine/carminechatter_burnbitch_loud02.ogg")
Schema.voices.Add("Carmine", "come on", "Wha agh-- Wh-Come on!", "vo/player/carmine/carminechatter_comeon_medium01.ogg")
Schema.voices.Add("Carmine", "come on not now", "D'auh. Come on.. Not now!", "vo/player/carmine/carminechatter_comeonnotnow_loud01.ogg")
Schema.voices.Add("Carmine", "come on you piece of shit", "Gahd' come on you piece of shit.. It's jammed!", "vo/player/carmine/carminechatter_comeonyoupieceofshit_medium01.ogg")
Schema.voices.Add("Carmine", "damnit theyre tough", "Damnit they're tough!", "vo/player/carmine/carminechatter_dammittheyretough_loud01.ogg")
Schema.voices.Add("Carmine", "damn grubs are tough", "Damn! Grubs are tough!", "vo/player/carmine/carminechatter_damngrubsaretough_loud01.ogg")
Schema.voices.Add("Carmine", "destroy it", "Destroy it!", "vo/player/carmine/carminechatter_destroyit_loud01.ogg")
Schema.voices.Add("Carmine", "dont do this to me now", "*Oh*-- come on, don't do that to *me now*!", "vo/player/carmine/carminechatter_dontdothattomenow_medium01.ogg")
Schema.voices.Add("Carmine", "dont mind if I do", "Don't mind if I do.", "vo/player/carmine/carminechatter_dontmindifido_medium01.ogg")
Schema.voices.Add("Carmine", "eat boot", "Eat boot!", "vo/player/carmine/carminechatter_eatboot_loud02.ogg")
Schema.voices.Add("Carmine", "eat dirt", "Eat dirt and die!", "vo/player/carmine/carminechatter_eatdirtanddie_loud01.ogg")
Schema.voices.Add("Carmine", "eat it", "*Eat it*!", "vo/player/carmine/carminechatter_eatit_loud02.ogg")
Schema.voices.Add("Carmine", "eat that", "Yeah, eat that!", "vo/player/carmine/carminechatter_eatthat_loud02.ogg")
Schema.voices.Add("Carmine", "engage", "Engage!", "vo/player/carmine/carminechatter_engage_loud02.ogg")
Schema.voices.Add("Carmine", "felt that one", "Haha! Felt that one!", "vo/player/carmine/carminechatter_feltthatone_loud01.ogg")
Schema.voices.Add("Carmine", "follow me", "Follow me!", "vo/player/carmine/carminechatter_followme_loud01.ogg")
Schema.voices.Add("Carmine", "form up", "Form up!", "vo/player/carmine/carminechatter_formup_loud01.ogg")
Schema.voices.Add("Carmine", "goodnight!", "Goodnight!", "vo/player/carmine/carminechatter_goodnight_loud02.ogg")
Schema.voices.Add("Carmine", "got another", "Got another!", "vo/player/carmine/carminechatter_gotanother_loud01.ogg")
Schema.voices.Add("Carmine", "got em", "Got 'em.", "vo/player/carmine/carminechatter_gotem_soft01.ogg")
Schema.voices.Add("Carmine", "got it.", "Got it.", "vo/player/carmine/carminechatter_gotit_medium01.ogg")
Schema.voices.Add("Carmine", "got some on me", "Woah! Got some on me!", "vo/player/carmine/carminechatter_gotsomeonme_loud01.ogg")
Schema.voices.Add("Carmine", "had to happen", "Had to happen!", "vo/player/carmine/carminechatter_hadtohappen_loud01.ogg")
Schema.voices.Add("Carmine", "in the zone", "I am in the *zone*!", "vo/player/carmine/carminechatter_iaminthezone_loud01.ogg")
Schema.voices.Add("Carmine", "like mine welldone", "I like mine well done!", "vo/player/carmine/carminechatter_ilikeminewelldone_loud03.ogg")
Schema.voices.Add("Carmine", "take those", "I'll take those.", "vo/player/carmine/carminechatter_illtakethose_medium01.ogg")
Schema.voices.Add("Carmine", "im out", "I'm out!", "vo/player/carmine/carminechatter_imout_loud01.ogg")
Schema.voices.Add("Carmine", "just die", "Agh, just die will ya?!", "vo/player/carmine/carminechatter_justdiewillya_loud01.ogg")
Schema.voices.Add("Carmine", "lets do this", "Lets do this!", "vo/player/carmine/carminechatter_letsdothis_loud01.ogg")
Schema.voices.Add("Carmine", "lock and load", "Lock and load!", "vo/player/carmine/carminechatter_lockandload_loud01.ogg")
Schema.voices.Add("Carmine", "look ma", "Look ma, no *face*!", "vo/player/carmine/carminechatter_lookmanoface_loud01.ogg")
Schema.voices.Add("Carmine", "medic", "Medic!", "vo/player/carmine/carminechatter_medic_loud01.ogg")
Schema.voices.Add("Carmine", "medic!", "*Medic!*", "vo/player/carmine/carminechatter_medic_loud02.ogg")
Schema.voices.Add("Carmine", "need ammo", "Agh, need ammo.", "vo/player/carmine/carminechatter_needammo_medium01.ogg")
Schema.voices.Add("Carmine", "next", "Next!", "vo/player/carmine/carminechatter_next_loud01.ogg")
Schema.voices.Add("Carmine", "nice", "Niice!", "vo/player/carmine/carminechatter_nice_loud01.ogg")
Schema.voices.Add("Carmine", "nighty night", "Nighty night!", "vo/player/carmine/carminechatter_nightynight_medium01.ogg")
Schema.voices.Add("Carmine", "not again", "Not *again*!", "vo/player/carmine/carminechatter_notagain_medium01.ogg")
Schema.voices.Add("Carmine", "oh yeah", "Oh *yeah*!", "vo/player/carmine/carminechatter_ohyeah_loud01.ogg")
Schema.voices.Add("Carmine", "safties off", "Safties off.", "vo/player/carmine/carminechatter_safetiesoff_medium01.ogg")
Schema.voices.Add("Carmine", "shit", "*Shhh*it!", "vo/player/carmine/carminechatter_shit_loud01.ogg")
Schema.voices.Add("Carmine", "shit!", "*Shhh*it!", "vo/player/carmine/carminechatter_shit_loud02.ogg")
Schema.voices.Add("Carmine", "shit yeah", "Shit yeah!", "vo/player/carmine/carminechatter_shityeah_loud01.ogg")
Schema.voices.Add("Carmine", "shoot it", "Shoot it!", "vo/player/carmine/carminechatter_shootit_loud01.ogg")
Schema.voices.Add("Carmine", "take cover", "Take cover!", "vo/player/carmine/carminechatter_takecover_loud02.ogg")
Schema.voices.Add("Carmine", "take it out", "Take it out!", "vo/player/carmine/carminechatter_takeitout_loud01.ogg")
Schema.voices.Add("Carmine", "theyre flanking", "They're flanking!", "vo/player/carmine/carminechatter_theyreflanking_loud01.ogg")
Schema.voices.Add("Carmine", "watch it", "Watch it!", "vo/player/carmine/carminechatter_watchit_loud01.ogg")
Schema.voices.Add("Carmine", "so screwed", "We're so screwed!", "vo/player/carmine/carminechatter_weresoscrewed_loud03.ogg")
Schema.voices.Add("Carmine", "whats the matter", "Ahaw-Whats the matter, You hurt?", "vo/player/carmine/carminechatter_whatsthematter_medium01.ogg")
Schema.voices.Add("Carmine", "youre out", "You're out!", "vo/player/carmine/carminechatter_youreout_loud03.ogg")
Schema.voices.Add("Carmine", "there you go", "Yeah, d'alright, there you go.", "vo/player/carmine/claytonchatter_alrightthereyougo_medium01.ogg")
Schema.voices.Add("Carmine", "bring it", "Come on, bring it!", "vo/player/carmine/claytonchatter_bringit_medium02.ogg")
Schema.voices.Add("Carmine", "clean up aisle five", "Clean up on aisle *fiive*!", "vo/player/carmine/claytonchatter_cleanuponislefive_loud01.ogg")
Schema.voices.Add("Carmine", "oops lost head", "*Oops*, you lost your head!", "vo/player/carmine/claytonchatter_oopsyoulostyourhead_loud01.ogg")
Schema.voices.Add("Carmine", "did I hurt you little baby", "D'aw I'm sorry, did I hurt you'lil'baby.. *FUCK YOU!*", "vo/player/carmine/claytonchatter_sorrydidthathurt_loud02.ogg")
Schema.voices.Add("Carmine", "live for", "Yeah, thats what I live for!", "vo/player/carmine/claytonchatter_thatswhatilivefor_loud01.ogg")
Schema.voices.Add("Carmine", "too close", "Ha-Hey! That was too close, you tryin' to kill me?!", "vo/player/carmine/claytonchatter_thatwastooclose_loud01.ogg")
Schema.voices.Add("Carmine", "times up", "Times up they're coming!", "vo/player/carmine/claytonchatter_timesuptheyrecoming_loud01.ogg")
Schema.voices.Add("Carmine", "enemies incomming", "We've got enemies incomming!", "vo/player/carmine/claytonchatter_wegotenemiesincoming_loud01.ogg")
Schema.voices.Add("Carmine", "yeeah", "*Yeeeaahhh!*", "vo/player/carmine/claytonchatter_yeah_loud01.ogg")
Schema.voices.Add("Carmine", "you cannot be serious", "Ug-D'aw.. You can *NOT* be *SERIOUS*!", "vo/player/carmine/claytonchatter_youcannotbeserious_loud01.ogg")
Schema.voices.Add("Carmine", "men sizes", "You guys come in men sizes?", "vo/player/carmine/claytonchatter_youcomeinmenssizes_med01.ogg")

Schema.voices.AddClass("Redshirt", function(client)
	return client:IsCOG()
end)

Schema.voices.AddClass("Carmine", function(client)
	return client:IsCOG()
end)